[workspace]
resolver = "2"
members = [
				"rknpu",
				"rknpu-cli",
				"rknpu-sys",
				"rknpu-runtime",
]

[workspace.dependencies]
anyhow = "1.0"
bindgen= "0.66"
criterion = "0.5.1"
half = "2.4.0"
image = "0.24.7"
imageproc = "0.23.0"
img = "0.1.0"
ndarray = "0.15.6"
thiserror = "1.0"
