use rknpu_sys::{
    RKNN_FLAG_ASYNC_MASK, RKNN_FLAG_COLLECT_MODEL_INFO_ONLY, RKNN_FLAG_COLLECT_PERF_MASK,
    RKNN_FLAG_EXECUTE_FALLBACK_PRIOR_DEVICE_GPU, RKNN_FLAG_FENCE_IN_OUTSIDE,
    RKNN_FLAG_FENCE_OUT_OUTSIDE, RKNN_FLAG_INTERNAL_ALLOC_OUTSIDE, RKNN_FLAG_MEM_ALLOC_OUTSIDE,
    RKNN_FLAG_PRIOR_HIGH, RKNN_FLAG_PRIOR_LOW, RKNN_FLAG_PRIOR_MEDIUM, RKNN_FLAG_SHARE_WEIGHT_MEM,
};

#[derive(Debug, Clone)]
#[allow(non_camel_case_types)]
#[repr(u32)]
pub enum RknnExtendedFlag {
    RKNN_FLAG_PRIOR_HIGH = RKNN_FLAG_PRIOR_HIGH,
    RKNN_FLAG_PRIOR_MEDIUM = RKNN_FLAG_PRIOR_MEDIUM,
    RKNN_FLAG_PRIOR_LOW = RKNN_FLAG_PRIOR_LOW,
    RKNN_FLAG_ASYNC_MASK = RKNN_FLAG_ASYNC_MASK,
    RKNN_FLAG_COLLECT_PERF_MASK = RKNN_FLAG_COLLECT_PERF_MASK,
    RKNN_FLAG_MEM_ALLOC_OUTSIDE = RKNN_FLAG_MEM_ALLOC_OUTSIDE,
    RKNN_FLAG_SHARE_WEIGHT_MEM = RKNN_FLAG_SHARE_WEIGHT_MEM,
    RKNN_FLAG_FENCE_IN_OUTSIDE = RKNN_FLAG_FENCE_IN_OUTSIDE,
    RKNN_FLAG_FENCE_OUT_OUTSIDE = RKNN_FLAG_FENCE_OUT_OUTSIDE,
    RKNN_FLAG_COLLECT_MODEL_INFO_ONLY = RKNN_FLAG_COLLECT_MODEL_INFO_ONLY,
    RKNN_FLAG_EXECUTE_FALLBACK_PRIOR_DEVICE_GPU = RKNN_FLAG_EXECUTE_FALLBACK_PRIOR_DEVICE_GPU,
    RKNN_FLAG_INTERNAL_ALLOC_OUTSIDE = RKNN_FLAG_INTERNAL_ALLOC_OUTSIDE,
}
